export const en = {
  common: {
    loading: 'Loading',
    next: 'Next',
    skip: 'Skip',
    previous: 'Previous',
    gender: 'Gender',
    male: 'Male',
    age: 'Age',
    contact: 'Contact',
    female: 'Female',
    other: 'Other',
    emptyData: 'No data available!',
    cancel: 'Cancel',
    yes: 'Yes',
    okay: 'Okay',
    alertTitle: 'Alert',
    ECG: 'ECG APP',
  },
  onboarding: {
    stepone: 'Step - 1',
    steptwo: 'Step - 2',
    onpatch: 'Turn ON the patch',
    onled: 'The red LEDs will alternately blink.',
    stepthree: 'Step - 3',
    attechdevice: 'Attach the Electrodes to the device at 1,2 & 3',
    stepfour: 'Step - 4',
    stepfive: 'Step - 5',
    attechchest: 'Attech the Device to the chest',
    centerchest: 'Position the Patch on the center of the chest',
    finger: 'Three fingers below collar bone to center of the Electrode',
    stepsix: 'Step - 6',
    correctposition: 'Patch show in correct position',
    stepseven: 'Step - 7',
    turnonapp: 'Turn ON the Mobile App',
    getstarted: 'Get Started',
  },
  login: {
    welcome: 'Welcome to ECG!',
    continue: 'Login to continue',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    forgotpassword: 'Forgot Password?',
    Signup: "Don't have an account? Signup",
    emailError: '* Please enter valid email!',
    passwordError: '* Please enter password!',
  },
  dashboard: {
    dashboard: 'Dashboard',
    welcome: 'Welcome!',
    username: 'Michelle Rose',
    bpmaverage: 'BPM Average',
    battery: 'Battery',
    device: 'Device',
    note: "Start tracking your heart's rhythm and electorical activity.",
    history: 'History',
    userguide: 'User Guide',
    profile: 'Profile',
    viewlive: 'View Live Streaming',
    percentage: '80%',
    connected: 'Connected',
  },
  ecgrecord: {
    normal: 'Patient is Normal',
    bpmaverage: 'BPM Average',
    sinus: 'Sinus tachycardia Otherwise Normal ECG',
    date: '14/08/21',
    heading: 'ECG Records',
  },
  livestreaming: {
    excellent: 'Excellent',
    parameters: 'Parameters',
    rrinterval: 'RR Interval',
    printerval: 'PR Interval',
    qtinterval: 'QT Interval',
    qrscomplex: 'QRS Complex',
    prsegment: 'PR Segment',
    stsegment: 'ST Segment',
    sec: 'Sec',
    bpm: 'BPM',
  },
  profile: {
    profile: 'Profile',
    edit: 'Edit',
    logout: 'Logout',
  },
  editprofile: {
    firstname: 'First Name',
    lastname: 'Last Name',
    email: 'Email',
    DOB: 'DOB',
    contact: 'Contact',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    save: 'Save',
  },
};
